name: "pr"
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-
      - run: npm ci
      - run: npm run all
      - name: Check for changes (fail if we forgot to update lib output)
        run: git diff --quiet lib
        continue-on-error: true
  self-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        with:
          url: ./template
          copyWithoutRender: |
            .static
          targetPath: ./output
          values: |
            {
              "name": "App",
              "type": "public"
            }
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # run assertion script
      - run: node output/index.js
  self-test-nested:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./ # Uses an action in the root directory
        with:
          url: ./template/deeply/nested_template
          copyWithoutRender: |
            .static
          targetPath: ./output
          values: |
            {
              "name": "App",
              "type": "public"
            }
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      # run assertion script
      - run: node output/index.js
